version: '3.8'

services:
  server:
    build:
      context: ./server
      args:
        - PORT=3000
    volumes:
      - ./server:/src
      - ./common:/common
    ports:
      - ${SERVER_PORT:-3000}:3000
    environment:
      - DB_USER=root_tp4
      - DB_PASSWORD=root_tp4
      - DB_NAME=TP4
      - DB_PORT=5432
      - DB_HOST=db
    networks:
      - default
      - postgres

  client:
    build:
      context: ./client
      args: 
        - PORT=4200
    volumes:
      - ./client:/src
      - ./common:/common
    ports:
      - 4200:4200
    command: ng serve --host 0.0.0.0 --port 4200
    environment:
      - NG_APP_SERVER_URL=http://localhost:${SERVER_PORT:-3000}

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root_tp4
      - POSTGRES_PASSWORD=root_tp4
      - POSTGRES_DB=TP4
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/data/postgres
    ports: 
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-root@root.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    logging:
      driver: none

networks:
  default:
    name: inf3710-tp4
  postgres:
    driver: bridge
  
volumes:
  postgres:
  pgadmin: