export const CATEGORIES = [
    "30 minutes",
    "À congeler",
    "Autocuiseur",
    "Cétogène",
    "Collation",
    "Comfort food",
    "Cuisine du monde",
    "Lunchs",
    "Mijoteuse",
    "Noël",
    "Petits prix",
    "Potluck",
    "Recettes sur la plaque",
    "Santé",
    "Végétarien",
    "Zéro gaspillage",
];
