export const CATEGORIES = [
    "30 minutes",
    "À congeler",
    "Autocuiseur",
    "Comfort food",
    "Cuisine du monde",
    "Cuisiner en lot",
    "Fait maison",
    "Jour de l'An",
    "Lunchs",
    "Mijoteuse",
    "Noël",
    "Nos meilleures recettes",
    "Petits prix",
    "Potluck",
    "Pour enfants",
    "Recettes de semaine",
    "Recettes du garde-manger",
    "Recettes sur la plaque",
    "Santé / Choix sain",
    "Snacks",
    "Sous vide",
    "Végétalien",
    "Végétarien",
    "Week-end au chalet",
    "Zéro gaspillage",
    "Voir tous les thèmes",
];
