export const Display = {
    flex: 'd--flex',
    justify: {
        between: 'd--flex--justify--between',
        around: 'd--flex--justify--around',
        start: 'd--flex--justify--start',
        end: 'd--flex--justify--end',
        center: 'd--flex--justify--center',
    },
    align: {
        center: 'd--flex--align--center',
        start: 'd--flex--align--start',
        end: 'd--flex--align--end',
    },
    gap: {
        0: 'd--gap-0',
        1: 'd--gap-1',
        2: 'd--gap-2',
        3: 'd--gap-3',
        4: 'd--gap-4',
        5: 'd--gap-5',
        6: 'd--gap-6',
    },
    margin: {
        0: 'd--m-0',
        1: 'd--m-1',
        2: 'd--m-2',
        3: 'd--m-3',
        4: 'd--m-4',
        5: 'd--m-5',
        6: 'd--m-6',
        top: {
            0: 'd--m-t-0',
            1: 'd--m-t-1',
            2: 'd--m-t-2',
            3: 'd--m-t-3',
            4: 'd--m-t-4',
            5: 'd--m-t-5',
            6: 'd--m-t-6',
        },
        bottom: {
            0: 'd--m-b-0',
            1: 'd--m-b-1',
            2: 'd--m-b-2',
            3: 'd--m-b-3',
            4: 'd--m-b-4',
            5: 'd--m-b-5',
            6: 'd--m-b-6',
        },
        left: {
            0: 'd--m-l-0',
            1: 'd--m-l-1',
            2: 'd--m-l-2',
            3: 'd--m-l-3',
            4: 'd--m-l-4',
            5: 'd--m-l-5',
            6: 'd--m-l-6',
        },
        right: {
            0: 'd--m-r-0',
            1: 'd--m-r-1',
            2: 'd--m-r-2',
            3: 'd--m-r-3',
            4: 'd--m-r-4',
            5: 'd--m-r-5',
            6: 'd--m-r-6',
        },
        horizontal: {
            0: 'd--m-h-0',
            1: 'd--m-h-1',
            2: 'd--m-h-2',
            3: 'd--m-h-3',
            4: 'd--m-h-4',
            5: 'd--m-h-5',
            6: 'd--m-h-6',
        },
        vertical: {
            0: 'd--m-v-0',
            1: 'd--m-v-1',
            2: 'd--m-v-2',
            3: 'd--m-v-3',
            4: 'd--m-v-4',
            5: 'd--m-v-5',
            6: 'd--m-v-6',
        },
    },
    padding: {
        0: 'd--p-0',
        1: 'd--p-1',
        2: 'd--p-2',
        3: 'd--p-3',
        4: 'd--p-4',
        5: 'd--p-5',
        6: 'd--p-6',
        top: {
            0: 'd--p-t-0',
            1: 'd--p-t-1',
            2: 'd--p-t-2',
            3: 'd--p-t-3',
            4: 'd--p-t-4',
            5: 'd--p-t-5',
            6: 'd--p-t-6',
        },
        bottom: {
            0: 'd--p-b-0',
            1: 'd--p-b-1',
            2: 'd--p-b-2',
            3: 'd--p-b-3',
            4: 'd--p-b-4',
            5: 'd--p-b-5',
            6: 'd--p-b-6',
        },
        left: {
            0: 'd--p-l-0',
            1: 'd--p-l-1',
            2: 'd--p-l-2',
            3: 'd--p-l-3',
            4: 'd--p-l-4',
            5: 'd--p-l-5',
            6: 'd--p-l-6',
        },
        right: {
            0: 'd--p-r-0',
            1: 'd--p-r-1',
            2: 'd--p-r-2',
            3: 'd--p-r-3',
            4: 'd--p-r-4',
            5: 'd--p-r-5',
            6: 'd--p-r-6',
        },
        horizontal: {
            0: 'd--p-h-0',
            1: 'd--p-h-1',
            2: 'd--p-h-2',
            3: 'd--p-h-3',
            4: 'd--p-h-4',
            5: 'd--p-h-5',
            6: 'd--p-h-6',
        },
        vertical: {
            0: 'd--p-v-0',
            1: 'd--p-v-1',
            2: 'd--p-v-2',
            3: 'd--p-v-3',
            4: 'd--p-v-4',
            5: 'd--p-v-5',
            6: 'd--p-v-6',
        },
    },
};

export const Typography = {
    h1: 't--h1',
    h2: 't--h2',
    h3: 't--h3',
    h4: 't--h4',
    h5: 't--h5',
    h6: 't--h6',

    decoration: {
        none: 't--d--n',
        underline: 't--d--under',
    },
    weight: {
        normal: 't--w--normal',
        semibold: 't--w--semibold',
        bold: 't--w--bold',
        extrabold: 't--w--extrabold',
    }
};

export const Colors = {
    white: 'c--white',
    black: 'c--black',
    faded: 'c--faded',
};

export const Screens = {
    only: {
        small: 's--only--small',
        medium: 's--only--medium',
        large: 's--only--large',
    },
    hide: {
        small: 's--hide--small',
        medium: 's--hide--medium',
        large: 's--hide--large',
    },
};

export const Helpers = {
    Display,
    Typography,
    Colors,
};